# RestFS COSTANTS
##############################################################################
PROPERTIES_ACP        = "ACP"
PROPERTIES_LOCATION   = "LOCATION"
PROPERTIES_WEBSITE    = "WEBSITE"
PROPERTIES_LOGGING    = "LOGGING"
PROPERTIES_VERSIONING = "VERSIONING"
PROPERTIES_BUCKET     = "PROPERTIES"



LOG_ENABLE  = True
LOG_DISABLE = False

VER_DISABLE = "Suspended"
VER_ENABLE  = "Enable"
VER_MFA_DISABLE = "Disabled"
VER_MFA_ENABLE = "Enable"
WEB_DISABLE = False
POLICY_DISABLE = False
NOTIFY_DISABLE = False

DISTRIBUTION_BASE = "BASE"

