USER_ANONYMOUS = 'anonymous'
USER_AUTHENTICATED = 'authenticated'


ADD_FILE     = "ADD_FILE"
ADD_SUBDIR   = "ADD_SUBDIR"
APPEND_DATA  = "APPEND_DATA"
DELETE_FILE  = "DELETE_FILE"
DELETE_CHILD = "DELETE_CHILD"
EXECUTE      = "EXECUTE"
LIST_DIR     = "LIST_DIR"
READ_ACL     = "READ_ACL"
READ_ATTR    = "READ_ATTR"
READ_DATA    = "READ_DATA"
READ_XATTR   = "READ_XATTR"
SYNC         = "SYNC"
LOCK         = "LOCK"
WRITE_ATTR   = "WRITE_ATTR"
WRITE_DATA   = "WRITE_DATA"
WRITE_XATTR  = "WRITE_XATTR"
WRITE_ACL    = "WRITE_ACL"
WRITE_OWNER  = "WRITE_OWNER"
ADMIN  = "ADMIN"

ALLOW = "ALLOW"
DENY  = "DENY"

FLAG  = "None"

